### 1. Import Lib & Read file

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

RAW_DATA_PATH = r'D:\MinhDuckDesktop\PROJECTS\DA\VietNam_Bank_Churn_Analysis\data\raw\bank_churn_dataset_80k.csv'

df_raw = pd.read_csv(RAW_DATA_PATH)
df_raw.head()

,id,full_name,credit_sco,gender,age,occupation,balance,monthly_ir,address,origin_province,tenure_ye,married,nums_card,nums_service,active_member,last_active_date,last_transaction_month,created_date,exit,customer_segment,engagement_score,loyalty_level,digital_behavior,risk_score,risk_segment,cluster_group
0,1,Đặng Văn Vũ,725,male,55,Chủ Doanh nghiệp nhỏ,177306004,121000000,Phường An Hội (BT),TP. Hồ Chí Minh,0,2,4,8,True,03/04/2025,91038993,27/02/2025,False,Priority,90,Bronze,mobile,0.0359,Low,4
1,2,Bùi Hữu Phúc,689,male,45,Nội trợ/Sinh viên,1927416,5000000,Phường Bến Thành (Q1),Đồng Nai,3,1,3,2,True,14/05/2025,3255569,29/07/2021,False,Mass,63,Gold,mobile,0.2664,Low,2
2,3,Lê Văn Mai,702,female,44,Chủ Doanh nghiệp nhỏ,304931745,109000000,Phường Hòa Bình (Q11),TP. Hồ Chí Minh,4,0,2,8,False,10/09/2021,0,03/03/2021,False,Priority,36,Silver,offline,0.1343,Low,4
3,4,Dương Trần Nhiên,766,male,44,Chủ Doanh nghiệp nhỏ,50615501,79000000,Phường 7 (Q7),TP. Hồ Chí Minh,3,0,4,3,False,04/03/2025,0,12/02/2022,False,Priority,23,Bronze,offline,0.2185,Low,4
4,5,Dương Thu Linh,677,female,77,Giáo viên/Giảng viên,40532432,25000000,Phường Thắng Lợi (Q10),TP. Hồ Chí Minh,2,1,4,3,False,06/08/2022,0,24/07/2022,False,Emerging,23,Bronze,offline,0.2942,Low,2

### 2. Check size & datatype

In [4]:
df_raw.shape
df_raw.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      80000 non-null  int64
 1   full_name               80000 non-null  str
 2   credit_sco              80000 non-null  int64
 3   gender                  80000 non-null  str
 4   age                     80000 non-null  int64
 5   occupation              80000 non-null  str
 6   balance                 80000 non-null  int64
 7   monthly_ir              80000 non-null  int64
 8   address                 80000 non-null  str
 9   origin_province         80000 non-null  str
 10  tenure_ye               80000 non-null  int64
 11  married                 80000 non-null  int64
 12  nums_card               80000 non-null  int64
 13  nums_service            80000 non-null  int64
 14  active_member           80000 non-null  bool
 15  last_active_date        80000 non-null  str
 16  last_transaction_month  80000 non-null  int64
 17  created_date            80000 non-null  str
 18  exit                    80000 non-null  bool
 19  customer_segment        80000 non-null  str
 20  engagement_score        80000 non-null  int64
 21  loyalty_level           80000 non-null  str
 22  digital_behavior        80000 non-null  str
 23  risk_score              80000 non-null  float64
 24  risk_segment            80000 non-null  str
 25  cluster_group           80000 non-null  int64
dtypes: bool(2), float64(1), int64(12), str(11)
memory usage: 14.8 MB

### 3. Missing / Duplicates & Describe

In [5]:
print("Missing values per column:\n", df_raw.isnull().sum())
print("\nDuplicate rows count:", df_raw.duplicated().sum())
print("\nDescriptive statistics:")
df_raw.describe().round(2)

Missing values per column:
 id                        0
full_name                 0
credit_sco                0
gender                    0
age                       0
occupation                0
balance                   0
monthly_ir                0
address                   0
origin_province           0
tenure_ye                 0
married                   0
nums_card                 0
nums_service              0
active_member             0
last_active_date          0
last_transaction_month    0
created_date              0
exit                      0
customer_segment          0
engagement_score          0
loyalty_level             0
digital_behavior          0
risk_score                0
risk_segment              0
cluster_group             0
dtype: int64

Duplicate rows count: 0

Descriptive statistics:

,id,credit_sco,age,balance,monthly_ir,tenure_ye,married,nums_card,nums_service,last_transaction_month,engagement_score,risk_score,cluster_group
count,80000.00,80000.00,80000.00,8.000000e+04,80000.0,80000.00,80000.00,80000.00,80000.00,8.000000e+04,80000.00,80000.00,80000.00
mean,40000.50,684.32,49.38,6.118320e+07,37788200.0,1.78,0.97,2.63,3.56,8.831755e+06,31.73,0.27,1.97
std,23094.16,51.17,15.07,8.868620e+07,36551066.2,1.32,0.69,1.22,2.00,3.378683e+07,23.47,0.09,1.04
min,1.00,495.00,20.00,4.086630e+05,3000000.0,0.00,0.00,1.00,1.00,0.000000e+00,7.00,0.02,1.00
25%,20000.75,649.00,38.00,1.462592e+07,14000000.0,1.00,1.00,2.00,2.00,0.000000e+00,16.00,0.20,1.00
50%,40000.50,682.00,47.00,3.090276e+07,23000000.0,2.00,1.00,2.00,3.00,0.000000e+00,22.00,0.28,2.00
75%,60000.25,718.00,58.00,6.960994e+07,47000000.0,3.00,1.00,3.00,5.00,0.000000e+00,38.00,0.34,2.00
max,80000.00,800.00,90.00,1.000000e+09,216000000.0,4.00,3.00,5.00,8.00,6.000000e+08,100.00,0.54,4.00

### 4. Check categorical data

In [6]:
cat_cols = df_raw.select_dtypes(include=['object', 'category', 'string']).columns

for col in cat_cols:
    print(f"Column: {col}")
    print(df_raw[col].value_counts())
    print("\n")

Column: full_name
full_name
Lê Minh Quang         42
Phạm Anh Quang        41
Vũ Đức Quang          41
Mai Thanh Quang       40
Mai Hữu Quang         38
Bùi Anh Quang         38
Lê Thu Quang          37
Trần Minh Quang       37
Bùi Minh Quang        37
Dương Hoàng Quang     37
Trần Thị Quang        36
Mai Đức Quang         36
Vũ Thu Quang          35
Dương Văn Quang       35
Phạm Thanh Quang      34
Lê Kim Quang          34
Đặng Thanh Lan        33
Dương Văn Vân         33
Đặng Quang Quang      33
Trần Gia Quang        33
Bùi Xuân Quang        33
Vũ Thanh Quang        33
Vũ Anh Quang          32
Bùi Thị Quang         32
Vũ Minh Ánh           32
Bùi Hữu Quang         32
Trần Hoàng Quang      32
Đặng Thu Quang        32
Trần Kim Quang        32
Nguyễn Thanh Quang    32
Bùi Hoàng Quang       32
Phạm Minh Quang       32
Lê Trần Quang         31
Nguyễn Thu Quang      31
Lê Thanh Quang        31
Hoàng Thị Quang       31
Hoàng Trần Quang      31
Hoàng Quang Quang     31
Dương Trần Quang      31
Nguyễn Hữu Duyên      31
Mai Thu Chi           31
Vũ Hữu Quang          31
Phạm Trần Quang       31
Mai Ngọc Ánh          31
Phạm Gia Quang        30
Vũ Kim Quang          30
Hoàng Minh Quang      30
Phạm Kim Minh         30
Hoàng Thanh Xuân      30
Nguyễn Đức Quang      30
Hoàng Xuân Quang      30
Dương Kim Quang       30
Nguyễn Quang Lan      30
Bùi Trần Quang        30
Bùi Đức Quang         30
Phạm Hữu Quang        30
Bùi Gia Quang         30
Phạm Xuân Quang       30
Bùi Anh Dương         30
Phạm Gia Mai          29
Trần Thanh Dương      29
Đặng Gia Quang        29
Phạm Quang Quang      29
Vũ Ngọc Thảo          29
Trần Hữu Quang        29
Dương Thanh Quang     29
Vũ Quang Yến          29
Bùi Xuân Hồng         29
Bùi Xuân Chi          29
Vũ Thị Quang          29
Đặng Văn Quang        29
Lê Kim Yến            29
Đặng Đức Quang        29
Đặng Kim Quang        29
Vũ Ngọc Xuân          29
Đặng Thanh Quang      29
Nguyễn Hữu Quang      28
Vũ Đức Thảo           28
Dương Ngọc Hương      28
Hoàng Thu Quang       28
Trần Văn Quang        28
Lê Văn Linh           28
Nguyễn Hoàng Quang    28
Nguyễn Xuân Lan       28
Đặng Thanh Ngọc       28
Đặng Đức Duyên        28
Trần Anh Yến          28
Vũ Quang Quang        28
Nguyễn Quang Thảo     28
Nguyễn Gia Quang      28
Hoàng Kim Quang       28
Trần Xuân Trọng       28
Phạm Văn Quang        28
Hoàng Kim Vân         28
Dương Quang Ngọc      28
Lê Gia Ngọc           28
Đặng Xuân Linh        28
Hoàng Hoàng Vi        28
Dương Ngọc Ánh        28
Trần Đức Dũng         28
Dương Hữu Dương       28
Trần Quang Quang      28
Nguyễn Hoàng Dương    28
Phạm Ngọc Quang       28
Nguyễn Ngọc Chi       27
Lê Trần Hồng          27
Bùi Ngọc Thảo         27
Trần Xuân Thảo        27
Vũ Anh Duyên          27
Trần Đức Hương        27
Dương Xuân Lan        27
Vũ Hữu Duyên          27
Phạm Kim Duyên        27
Đặng Kim Chi          27
Trần Xuân Quang       27
Nguyễn Xuân Quang     27
Mai Kim Thảo          27
Hoàng Đức Mai         27
Hoàng Gia Duyên       27
Trần Văn Mai          27
Dương Thu Quang       27
Vũ Hoàng Ánh          27
Nguyễn Minh Quang     27
Bùi Thanh Quang       27
Dương Gia Vi          27
Hoàng Thị Mai         27
Bùi Trần Lan          27
Dương Quang Hồng      27
Đặng Minh Xuân        27
Phạm Xuân Ánh         27
Đặng Anh Thảo         27
Lê Minh Dương         27
Lê Hữu Quang          27
Vũ Thanh Ánh          27
Phạm Thị Yến          27
Dương Gia Yến         27
Dương Thanh Vân       27
Trần Trần Thảo        27
Vũ Thu Ánh            27
Mai Thị Thảo          27
Dương Quang Quang     27
Trần Hoàng Chi        27
Hoàng Hữu Hương       27
Bùi Quang Quang       27
Lê Hoàng Quang        27
Mai Đức Linh          27
Phạm Hoàng Lan        27
Nguyễn Đức Vân        27
Nguyễn Trần Vũ        27
Hoàng Hoàng Hồng      27
Dương Anh Quang       26
Nguyễn Thị Hương      26
Dương Xuân Quang      26
Lê Minh Ánh           26
Dương Trần Duyên      26
Bùi Kim Vi            26
Phạm Gia Lan          26
Bùi Ngọc Ngọc         26
Nguyễn Văn Quang      26
Vũ Xuân Quang         26
Dương Hoàng Vân       26
Dương Thị Chi         26
Vũ Văn Xuân           26
Hoàng Gia Chi         26
Trần Hoàng Duyên      26
Mai Kim Chi           26
Lê Hoàng Hương        26
Vũ Gia Thảo           26
Dương Anh Mai         26
Bùi Xuân Ngọc         26
Phạm Hoàng Thảo       26
Hoàng Hoàng Ngọc      26
Dương Anh Ngọc        26
Mai Thu Quang         26
Hoàng Xuân Hồng       26
Dương Hoàng Hồng      26
Lê Xuân Hương         26
Dương Thu Chi         26
Dương Trần Dương      26
Dương Xuân Tùng       26
Phạm Xuân Tùng        26
Bùi Anh Yến           26
Dương Xuân Ngọc       26
Lê Xuân Quang         26
Vũ Thị Vi             26
Nguyễn Thu Hồng       26
Dương Kim Dương       26
Lê Thanh Yến          26
Lê Thị Quang          26
Vũ Gia Quang          26
Hoàng Thanh Quang     26
Hoàng Minh Hương      26
Vũ Quang Dương        26
Đặng Quang Hương      26
Trần Hữu Dương        26
Lê Hoàng Lan          26
Đặng Hữu Chi          26
Mai Thị Vân           26
Vũ Văn Quang          25
Đặng Thị Quang        25
Vũ Thị Mai            25
Vũ Hữu Hương          25
Hoàng Thu Mai         25
Mai Văn Quang         25
Dương Hoàng Mai       25
Trần Kim Hồng         25
Mai Ngọc Hương        25
Hoàng Trần Vân        25
Đặng Đức Ngọc         25
Đặng Trần Hương       25
Dương Kim Vi          25
Trần Ngọc Quang       25
Nguyễn Xuân Huy       25
Phạm Đức Lan          25
Mai Anh Yến           25
Dương Thị Thảo        25
Hoàng Gia Quang       25
Phạm Thị Mai          25
Mai Văn Thảo          25
Dương Hữu Mai         25
Trần Văn Dương        25
Trần Xuân Lan         25
Nguyễn Hoàng Ánh      25
Bùi Văn Phúc          25
Lê Hoàng Linh         25
Phạm Kim Yến          25
Đặng Văn Xuân         25
Dương Trần Yến        25
Mai Thu Lan           25
Trần Kim Lan          25
Đặng Đức Vân          25
Lê Anh Quang          25
Trần Thanh Hương      25
Lê Ngọc Lan           25
Phạm Kim Quang        25
Lê Thu Ánh            25
Lê Văn Lan            25
Lê Quang Ngọc         25
Mai Anh Vi            25
Bùi Hữu Hương         25
Phạm Hoàng Quang      25
Lê Thị Mai            25
Nguyễn Kim Chi        25
Nguyễn Văn Vi         25
Phạm Minh Vi          25
Nguyễn Ngọc Quang     25
Nguyễn Thanh Dương    25
Phạm Thị Quang        25
Phạm Đức Linh         25
Mai Anh Lan           25
Trần Hoàng Ánh        25
Lê Gia Vân            25
Nguyễn Thị Vân        25
Phạm Thu Yến          25
Lê Thị Thảo           25
Trần Gia Hồng         25
Nguyễn Anh Quang      25
Vũ Minh Quang         25
Đặng Trần Ngọc        25
Bùi Kim Duyên         25
Bùi Trần Dương        25
Lê Thu Lan            25
Trần Gia Xuân         24
Hoàng Minh Tú         24
Mai Hoàng Quang       24
Trần Minh Hồng        24
Bùi Đức Lan           24
Dương Đức Quang       24
Bùi Quang Vân         24
Phạm Văn Dương        24
Vũ Hoàng Hồng         24
Đặng Trần Chi         24
Đặng Thu Hương        24
Phạm Thanh Ánh        24
Nguyễn Văn Bảo        24
Lê Thị Lan            24
Nguyễn Kim Dũng       24
Phạm Xuân Mai         24
Dương Trần Phúc       24
Bùi Thị Xuân          24
Trần Ngọc Thảo        24
Phạm Hoàng Duyên      24
Nguyễn Kim Linh       24
Vũ Trần Dương         24
Vũ Minh Hoàng         24
Nguyễn Minh Ánh       24
Đặng Xuân Ánh         24
Bùi Anh Hồng          24
Lê Thu Xuân           24
Bùi Kim Yến           24
Bùi Ngọc Ánh          24
Lê Gia Quang          24
Đặng Đức Lan          24
Vũ Quang Vi           24
Lê Gia Hương          24
Đặng Thanh Mai        24
Vũ Hữu Dương          24
Lê Thu Chi            24
Vũ Quang Hồng         24
Vũ Văn Chi            24
Trần Thanh Thảo       24
Bùi Ngọc Chi          24
Hoàng Anh Yến         24
Nguyễn Thu Dương      24
Nguyễn Xuân Yến       24
Bùi Thu Lan           24
Phạm Anh Chi          24
Vũ Xuân Minh          24
Dương Đức Vân         24
Trần Minh Ngọc        24
Vũ Thanh Hồng         24
Mai Thị Quang         24
Vũ Thanh Lan          24
Trần Trần Linh        24
Nguyễn Văn Chi        24
Đặng Hoàng Khoa       24
Bùi Thu Mai           24
Nguyễn Quang Linh     24
Phạm Thị Duyên        24
Vũ Đức Vi             24
Hoàng Thu Lan         24
Bùi Ngọc Hương        24
Bùi Đức Hồng          24
Bùi Xuân Linh         24
Hoàng Đức Quang       24
Mai Gia Vân           24
Hoàng Hữu Tú          24
Hoàng Gia Hương       24
Hoàng Đức Thảo        24
Phạm Xuân Yến         24
Bùi Ngọc Quang        24
Mai Ngọc Quang        24
Lê Văn Quang          24
Mai Anh Quang         24
Lê Xuân Chi           24
Vũ Hữu Mai            24
Mai Minh Lan          24
Nguyễn Quang Xuân     24
Lê Hoàng Duyên        24
Nguyễn Gia Duyên      24
Mai Quang Yến         24
Dương Văn Xuân        24
Phạm Thị Hương        24
Đặng Anh Hồng         24
Mai Minh Quang        24
Phạm Quang Lan        24
Đặng Anh Quang        24
Nguyễn Anh Ngọc       23
Hoàng Thu Ngọc        23
Mai Minh Nam          23
Nguyễn Anh Xuân       23
Bùi Thị Lan           23
Bùi Thu Vũ            23
Trần Trần Hồng        23
Mai Hoàng Phúc        23
Vũ Thu Hồng           23
Đặng Kim Yến          23
Vũ Kim Vân            23
Mai Minh Vân          23
Mai Anh Chi           23
Hoàng Trần Hồng       23
Hoàng Văn Duyên       23
Lê Xuân Dương         23
Nguyễn Thanh Hương    23
Vũ Ngọc Chi           23
Hoàng Văn Ngọc        23
Bùi Thu Ngọc          23
Mai Thanh Duyên       23
Mai Thu Xuân          23
Hoàng Trần Chi        23
Lê Thị Tú             23
Đặng Xuân Trọng       23
Trần Trần Xuân        23
Mai Thị Duyên         23
Trần Văn Vân          23
Đặng Văn Ánh          23
Lê Đức Hồng           23
Nguyễn Văn Hồng       23
Bùi Kim Hương         23
Hoàng Thị Lan         23
Trần Thu Duyên        23
Mai Trần Dương        23
Đặng Hoàng Mai        23
Hoàng Hữu Mai         23
Dương Minh Châu       23
Bùi Thanh Thảo        23
Trần Anh Hồng         23
Bùi Ngọc Yến          23
Đặng Thu Thành        23
Mai Hoàng Mai         23
Trần Thu Quang        23
Lê Hữu Xuân           23
Bùi Kim Quang         23
Hoàng Gia Thảo        23
Hoàng Văn Quang       23
Bùi Xuân Thảo         23
Mai Đức Thảo          23
Lê Đức Dương          23
Vũ Hữu Xuân           23
Trần Hoàng Thành      23
Bùi Thanh Phúc        23
Bùi Đức Hương         23
Hoàng Ngọc Ngọc       23
Hoàng Trần Mai        23
Mai Trần Quang        23
Hoàng Ngọc Ánh        23
Phạm Trần Khoa        23
Mai Kim Linh          23
Phạm Thu Thảo         23
Trần Thị Lan          23
Nguyễn Ngọc Lan       23
Lê Xuân Nam           23
Hoàng Thị Dũng        23
Dương Trần Vi         23
Mai Kim Quang         23
Bùi Xuân Hưng         23
Hoàng Thị Hương       23
Vũ Đức Mai            23
Mai Quang Linh        23
Lê Ngọc Thảo          23
Nguyễn Kim Mai        23
Lê Xuân Lan           23
Nguyễn Thị Tú         23
Vũ Thị Chi            23
Hoàng Hữu Hồng        23
Vũ Anh Thành          23
Mai Hoàng Duyên       23
Trần Hữu Yến          23
Bùi Minh Xuân         23
Bùi Quang Anh         23
Lê Anh Lan            23
Dương Đức Mai         23
Phạm Xuân Nhiên       23
Lê Đức Yến            23
Bùi Minh Chi          23
Phạm Kim Ngọc         23
Phạm Kim Hồng         23
Trần Anh Quang        23
Nguyễn Xuân Trọng     23
Hoàng Hữu Quang       23
Vũ Gia Lan            23
Nguyễn Đức Châu       23
Bùi Anh Hương         23
Trần Thu Châu         23
Hoàng Kim Hồng        23
Nguyễn Thị Linh       22
Lê Ngọc Linh          22
Dương Đức Hồng        22
Mai Hữu Tùng          22
Nguyễn Đức Mai        22
Hoàng Xuân Chi        22
Hoàng Gia Dương       22
Phạm Đức Yến          22
Hoàng Quang Yến       22
Dương Minh Hoàng      22
Mai Gia Lan           22
Mai Xuân Chi          22
Bùi Kim Lan           22
Phạm Kim Vân          22
Vũ Quang Linh         22
Nguyễn Minh Tú        22
Lê Xuân Mai           22
Vũ Văn Duyên          22
Phạm Đức Quang        22
Trần Ngọc Duyên       22
Dương Minh Vi         22
Vũ Thanh Bảo          22
Đặng Kim Xuân         22
Phạm Gia Dương        22
Hoàng Ngọc Duyên      22
Vũ Kim Mai            22
Nguyễn Quang Yến      22
Lê Gia Duyên          22
Trần Thu Vi           22
Hoàng Trần Lan        22
Dương Quang Duyên     22
Đặng Hoàng Hồng       22
Vũ Xuân Vi            22
Trần Thị Hồng         22
Hoàng Thu Hồng        22
Mai Kim Lan           22
Dương Hữu Vi          22
Nguyễn Thị Quang      22
Nguyễn Trần Dương     22
Hoàng Quang Vũ        22
Trần Đức Trọng        22
Bùi Kim Chi           22
Nguyễn Thanh Ánh      22
Hoàng Đức Nhiên       22
Phạm Hữu Hương        22
Hoàng Thu Ánh         22
Hoàng Đức Hương       22
Dương Kim Ánh         22
Đặng Văn Hồng         22
Phạm Kim Xuân         22
Hoàng Gia Yến         22
Hoàng Thị Huy         22
Lê Đức Vi             22
Dương Thanh Mai       22
Trần Hoàng Vi         22
Mai Minh Hồng         22
Mai Hữu Hoàng         22
Hoàng Minh Lan        22
Trần Ngọc Vi          22
Trần Đức Xuân         22
Bùi Thanh Dương       22
Dương Kim Linh        22
Đặng Văn Vân          22
Mai Văn Linh          22
Phạm Thanh Thảo       22
Mai Thu Thảo          22
Bùi Hoàng Lan         22
Mai Xuân Quang        22
Trần Văn Duyên        22
Dương Thu Lan         22
Vũ Anh Mai            22
Vũ Thanh Dương        22
Nguyễn Gia Huy        22
Hoàng Ngọc Vân        22
Vũ Xuân Chi           22
Mai Hoàng Yến         22
Dương Thị Dương       22
Nguyễn Kim Yến        22
Phạm Hoàng Dương      22
Vũ Đức Lan            22
Hoàng Anh Lan         22
Hoàng Quang Vi        22
Nguyễn Xuân Thành     22
Dương Văn Linh        22
Nguyễn Ngọc Linh      22
Mai Thanh Mai         22
Dương Trần Vân        22
Vũ Anh Trung          22
Phạm Văn Châu         22
Dương Hoàng Hương     22
Phạm Thanh Vi         22
Vũ Thu Lan            22
Bùi Trần Vi           22
Lê Thanh Vân          22
Bùi Thanh Lan         22
Vũ Minh Vi            22
Mai Văn Phúc          22
Bùi Văn Quang         22
Bùi Xuân Lan          22
Nguyễn Thị Vi         22
Hoàng Hữu Hoàng       22
Phạm Anh Vân          22
Nguyễn Văn Hoàng      22
Bùi Kim Ánh           22
Lê Thị Xuân           22
Dương Minh Xuân       22
Phạm Ngọc Xuân        22
Hoàng Hoàng Thảo      22
Bùi Quang Vi          22
Phạm Thu Vi           22
Đặng Anh Huy          22
Trần Hữu Huy          22
Mai Hoàng Ánh         22
Mai Thu Duyên         22
Dương Hoàng Xuân      22
Hoàng Anh Quang       22
Nguyễn Thanh Vân      22
Mai Anh Dương         22
Mai Anh Duyên         22
Dương Xuân Hồng       22
Nguyễn Hữu Hồng       22
Dương Hữu Duyên       22
Hoàng Kim Hương       22
Vũ Đức Chi            22
Lê Văn Thảo           22
Phạm Trần Bảo         22
Trần Văn Thành        22
Bùi Hoàng Xuân        22
Vũ Quang Mai          22
Phạm Minh Duyên       22
Đặng Đức Hưng         22
Lê Anh Duyên          22
Phạm Trần Hương       22
Dương Minh Linh       22
Vũ Minh Thành         22
Lê Thị Huy            22
Trần Thu Yến          22
Vũ Kim Ánh            22
Đặng Quang Dương      22
Dương Gia Quang       22
Đặng Xuân Quang       22
Nguyễn Văn Dương      22
Vũ Hữu Bảo            22
Mai Xuân Ngọc         22
Bùi Ngọc Duyên        22
Phạm Thu Chi          22
Nguyễn Văn Mai        22
Phạm Gia Thảo         21
Phạm Thanh Bảo        21
Lê Gia Yến            21
Hoàng Thị Bảo         21
Phạm Ngọc Chi         21
Lê Thanh Mai          21
Vũ Ngọc Linh          21
Mai Hoàng Nam         21
Bùi Anh Vi            21
Bùi Quang Ngọc        21
Nguyễn Đức Yến        21
Bùi Xuân Vân          21
Trần Thanh Xuân       21
Trần Hoàng Xuân       21
Dương Anh Lan         21
Nguyễn Minh Khoa      21
Phạm Thị Dương        21
Lê Anh Ánh            21
Vũ Văn Hương          21
Mai Thanh Yến         21
Phạm Ngọc Vi          21
Bùi Xuân Dương        21
Đặng Xuân Ngọc        21
Mai Anh Hồng          21
Bùi Hoàng Thảo        21
Nguyễn Hữu Thảo       21
Bùi Thu Quang         21
Vũ Quang Duyên        21
Mai Xuân Ánh          21
Nguyễn Hữu Xuân       21
Phạm Ngọc Hương       21
Đặng Đức Huy          21
Phạm Ngọc Vân         21
Trần Xuân Ánh         21
Lê Thị Nhiên          21
Lê Hữu Lan            21
Trần Quang Thảo       21
Lê Thị Tùng           21
Lê Anh Ngọc           21
Nguyễn Anh Dũng       21
Phạm Quang Nam        21
Đặng Trần Quang       21
Lê Gia Ánh            21
Lê Quang Chi          21
Phạm Thị Ánh          21
Bùi Quang Trọng       21
Hoàng Văn Lan         21
Đặng Xuân Yến         21
Nguyễn Thu Duyên      21
Đặng Trần Duyên       21
Đặng Ngọc Quang       21
Dương Thu Dương       21
Mai Gia Hồng          21
Bùi Thị Dương         21
Đặng Gia Xuân         21
Vũ Ngọc Dương         21
Bùi Quang Dương       21
Hoàng Hoàng Quang     21
Đặng Đức Ánh          21
Vũ Hữu Ánh            21
Mai Xuân Duyên        21
Nguyễn Thu Bảo        21
Phạm Thị Chi          21
Hoàng Kim Ánh         21
Trần Kim Phúc         21
Mai Ngọc Duyên        21
Dương Thị Hồng        21
Dương Gia Hưng        21
Trần Kim Vi           21
Phạm Anh Linh         21
Bùi Thu Dương         21
Nguyễn Văn Xuân       21
Trần Thanh Nam        21
Mai Minh Xuân         21
Lê Đức Thảo           21
Bùi Quang Thảo        21
Đặng Trần Vi          21
Bùi Ngọc Mai          21
Trần Thanh Hưng       21
Trần Quang Vân        21
Dương Trần Thảo       21
Hoàng Thị Hồng        21
Đặng Gia Duyên        21
Vũ Thanh Ngọc         21
Dương Quang Linh      21
Phạm Ngọc Khoa        21
Bùi Thu Duyên         21
Bùi Kim Xuân          21
Dương Quang Tú        21
Trần Minh Duyên       21
Đặng Văn Duyên        21
Dương Xuân Yến        21
Hoàng Thị Yến         21
Hoàng Hoàng Lan       21
Nguyễn Quang Hồng     21
Trần Quang Vi         21
Trần Kim Mai          21
Lê Đức Quang          21
Lê Minh Nhiên         21
Lê Hoàng Vi           21
Mai Hữu Xuân          21
Phạm Ngọc Nhiên       21
Vũ Quang Ánh          21
Lê Hữu Hồng           21
Dương Hữu Lan         21
Phạm Xuân Xuân        21
Bùi Hoàng Hưng        21
Mai Minh Mai          21
Nguyễn Thanh Yến      21
Dương Hữu Ánh         21
Dương Văn Nam         21
Hoàng Gia Tú          21
Mai Gia Duyên         21
Lê Trần Vi            21
Lê Ngọc Ngọc          21
Hoàng Anh Chi         21
Đặng Thanh Ánh        21
Trần Trần Dương       21
Mai Văn Duyên         21
Bùi Trần Vân          21
Đặng Minh Hương       21
Nguyễn Trần Nam       21
Lê Minh Hồng          21
Nguyễn Văn Tùng       21
Vũ Hoàng Khoa         21
Lê Thị Anh            21
Phạm Thu Linh         21
Lê Anh Xuân           21
Mai Kim Vân           21
Phạm Thanh Trung      21
Mai Thu Ánh           21
Vũ Ngọc Duyên         21
Đặng Anh Xuân         21
Đặng Hữu Ngọc         21
Trần Thanh Ngọc       21
Vũ Trần Duyên         21
Vũ Trần Dũng          21
Dương Ngọc Bảo        21
Lê Xuân Vân           21
Vũ Trần Xuân          21
Bùi Văn Vân           21
Nguyễn Gia Xuân       21
Vũ Thị Yến            21
Hoàng Thu Thảo        21
Nguyễn Anh Yến        21
Vũ Hữu Thảo           21
Lê Văn Hương          21
Hoàng Quang Linh      21
Dương Anh Thảo        21
Mai Minh Phúc         21
Bùi Thanh Linh        21
Hoàng Thu Linh        21
Lê Thị Yến            21
Trần Văn Linh         21
Mai Kim Mai           21
Dương Gia Nhiên       21
Đặng Văn Linh         21
Mai Thu Vân           21
Lê Ngọc Vân           21
Vũ Xuân Thảo          21
Đặng Xuân Hưng        21
Phạm Gia Xuân         21
Bùi Xuân Anh          21
Bùi Trần Chi          21
Trần Anh Duyên        21
Đặng Minh Vũ          21
Bùi Văn Hồng          21
Đặng Gia Dương        21
Nguyễn Quang Quang    21
Hoàng Xuân Bảo        21
Lê Hoàng Châu         21
Mai Hữu Mai           21
Đặng Hữu Hương        21
Bùi Trần Yến          21
Mai Thanh Chi         21
Phạm Đức Ngọc         21
Bùi Kim Dương         21
Đặng Hữu Thảo         21
Lê Anh Vũ             21
Nguyễn Hoàng Vi       21
Phạm Thanh Dương      21
Lê Quang Quang        21
Trần Quang Dương      21
Vũ Gia Linh           21
Phạm Hữu Vi           21
Trần Thu Vân          21
Trần Quang Ánh        21
Lê Ngọc Bảo           21
Mai Trần Trung        21
Hoàng Thanh Lan       21
Hoàng Quang Hoàng     21
Mai Quang Trung       21
Lê Hữu Vi             21
Lê Ngọc Hương         21
Hoàng Thu Dương       21
Hoàng Kim Dương       20
Bùi Hoàng Vi          20
Bùi Kim Linh          20
Nguyễn Đức Duyên      20
Trần Kim Thảo         20
Trần Thị Vi           20
Phạm Đức Duyên        20
Trần Đức Vân          20
Dương Thị Xuân        20
Dương Anh Yến         20
Nguyễn Trần Mai       20

### 5. Data Quality Assessment Report

**Kích thước & Cấu trúc (Volume & Schema):**

- Tập dữ liệu gồm 80,000 dòng và 26 cột.

- Đầy đủ các trường thuộc tính từ thông tin cá nhân, chỉ số tài chính, lịch sử giao dịch cho đến phân nhóm rủi ro (risk_segment, cluster_group).

**Độ toàn vẹn (Integrity & Health Check):**

- Missing values: 0 (Toàn bộ 80,000 dòng ở 26 cột đều non-null).

**Phân phối chỉ số số (Numeric summary):**

- Độ tuổi (age): Từ 20 đến 90 tuổi (trung bình 49.38), hợp lý.

- Điểm tín dụng (credit_score): Từ 495 đến 800.

- Số dư (balance): Không có giá trị âm.

### 6. Export raw data to DataLake

In [12]:
import os
import dotenv
import sys
sys.path.append(os.path.abspath(".."))
from src.db_connection import get_db_engine 

dotenv.load_dotenv()

table_name = os.getenv('TB_NAME_RAW_BANK_CHURN')
DB_NAME_DATALAKE = os.getenv('DB_NAME_DATALAKE')
engine = get_db_engine(DB_NAME_DATALAKE)
try:
    df_raw.to_sql(name=table_name, con=engine, if_exists='replace', index=False)
except Exception as e:
    print(f"An error occurred: {e}")